- id: '1614058820063'
  alias: Motion-activated Switch
  description: ''
  use_blueprint:
    path: homeassistant/motion_switch.yaml
    input:
      no_motion_wait: '0'
      motion_entity: binary_sensor.laundry_occupancy
      switch_target:
        entity_id: switch.laundry_main
